version: "3"
services:
    server:
      build: server
      ports:
        - "8080:8080"
    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      volumes:
        - ./init:/docker-entrypoint-initdb.d/